# config/profile/equities.yaml
ibkr:
  what_to_show: TRADES
  bar_size_secs: 60

execution:
  be_lock_min: 12
  be_req_profit_ticks: 2
  max_hold_min: 40
  hard_cutoff_R: -0.25
  hard_cutoff_min: 10
  min_minutes_to_window_end: 20
  avoid_market_orders: true
  limit_slippage_ticks: 2
  tif: DAY           # <- different from futures
  outside_rth: false # <- different from futures

timezone: America/Chicago
strategy:
  orb_minutes: 5
  atr_len: 14
  atr_mult: 0.7
  target_R: 1.0
  slope_min: 0.06
  break_eps_ticks: 1
  stop_pad_ticks: 1
  trail_pad_ticks: 1
  session_windows:
    - ["08:30", "15:00"]   # <- equities hours
