ES:
  symbol: "ES"
  exchange: CME
  currency: USD
  tick_size: 0.25
  tick_value: 12.5      
  commission_per_contract: 2.25
  exchange_fees_per_contract: 2.00

MES:
  symbol: "MES"
  exchange: CME
  currency: USD
  tick_size: 0.25
  tick_value: 1.25       
  commission_per_contract: 0.50
  exchange_fees_per_contract: 0.00

SPY:
  symbol: SPY
  exchange: SMART
  currency: USD
  tick_size: 0.01
  tick_value: 0.01           
  commission_per_contract: 0.005
  exchange_fees_per_contract: 0.00

QQQ:
  symbol: QQQ
  exchange: SMART
  currency: USD
  tick_size: 0.01
  tick_value: 0.01
  commission_per_contract: 0.005
  exchange_fees_per_contract: 0.00

